CREATE TABLE instructor(
	id_instructor TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nombres VARCHAR(15) NOT NULL,
	apellidos VARCHAR(15) NOT NULL,
	documento CHAR(10) NOT NULL,
	disciplina VARCHAR(20),
	id_clase SMALLINT UNSIGNED NOT NULL,
	id_contrato TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY(id_clase) REFERENCES clase(id_clase)
	ON DELETE CASCASDE ON UPDATE CASCADE,
	FOREIGN KEY(id_contrato) REFERENCES contrato(id_contrato)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;
