CREATE TABLE horarioClase(
	id_clase SMALLINT UNSIGNED NOT NULL,
	id_horario SMALLINT UNSIGNED NOT NULL,
	FOREIGN KEY(id_clase) REFERENCES clase(id_clase)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(id_horario) REFERENCES horario(id_horario)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;
